### ISSUE TITLE
moon zenith and moon phase determination

### ISSUE THREAD

**Issue by Zakalicious** [nikolajjensen/SunCalc#2]
I don't see variables for moon phase at a given time or the moon zenith. 
Do I have to iterate over a day to find the zenith?

Thanks

**Comment by nikolajjensen** [comment]
Thanks for your interest in Suncalc!

**Moon Phase**
To find the moon phase at a given time, have a look at this example for Copenhagen:
```swift
let moonIllumination = try MoonIllumination.compute()
                                            .on(year: 2021, month: 11, day: 13, hour: 17, minute: 49, second: 0)
                                            .timezone(TimeZone(identifier: "Europe/Copenhagen")!)
                                            .at(55.6761, 12.5683)
                                            .execute()
        
print("Moon illumination/visibility is: ", moonIllumination.fraction)
print("Moon closest phase is: ", moonIllumination.closestPhase.angle)
```
I would encourage you to have a look at the  `Phase` class, as it is used to find the closest phase.
You may also be interested in having a closer look at the `phase` defined in the `MoonIllumination` class which is used to derive the the closest phase. It is defined as follows:
```swift
/// Moon phase.
///
/// Starts at -180.0 (new moon, waxing), passes 0.0 (full moon) and moves towards 180.0 (waning, new moon).
/// Note that for historical reasons, the range of this phase is different to the moon phase angle used in MoonPhase.
public let phase: Double
```

**Moon Zenith**
To find the the moon zenith angle at a given point in time, have a look at this example:
```swift
let moonPosition = try MoonPosition.compute()
                                        .on(year: 2021, month: 11, day: 13, hour: 17, minute: 49, second: 0)
                                        .timezone(TimeZone(identifier: "Europe/Copenhagen")!)
                                        .at(55.6761, 12.5683)
                                        .execute()
        
print("The angle is: ", moonPosition.altitude)
print("The zenith angle is: ", 90 - moonPosition.altitude)
```

On the other hand, if want to find the time at the highest zenith - or if you would like to know the zenith over time (for a graph, perhaps) - you would need to calculate the `MoonPosition` for each data point in your time window. From that you can extrapolate the peak.

Hope this helps!

**Comment by Zakalicious** [comment]
Got it.

Thanks for the info and great work.

Regards, Thomas
